# Generated by Django 4.0.5 on 2023-10-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lignindb', '0002_ncbidb'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncbidb',
            name='product',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
