# Generated by Django 4.0.5 on 2023-10-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lignindb', '0003_ncbidb_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncbidb',
            name='sequence',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
