# Generated by Django 4.0.5 on 2023-10-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lignindb', '0004_ncbidb_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncbidb',
            name='pathways',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
