# Generated by Django 4.0.5 on 2023-10-18 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lignindb', '0006_pagetab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagetab',
            name='gene',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='pagetab',
            name='pathways',
            field=models.CharField(max_length=500),
        ),
    ]
