# Generated by Django 4.0.5 on 2023-10-18 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lignindb', '0007_alter_pagetab_gene_alter_pagetab_pathways'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagetab',
            name='gene',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pagetab',
            name='pathways',
            field=models.TextField(),
        ),
    ]
