# Generated by Django 4.0.5 on 2023-11-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lignindb', '0008_alter_pagetab_gene_alter_pagetab_pathways'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagetab',
            name='taxonomy',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
