# Generated by Django 4.0.5 on 2023-11-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lignindb', '0009_pagetab_taxonomy'),
    ]

    operations = [
        migrations.CreateModel(
            name='taxonomytb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org', models.CharField(max_length=200)),
                ('comptax', models.CharField(max_length=200)),
                ('taxonomy1', models.CharField(max_length=200)),
                ('taxonomy2', models.CharField(max_length=200)),
                ('taxonomy3', models.CharField(max_length=200)),
                ('taxonomy4', models.CharField(max_length=200)),
                ('taxonomy5', models.CharField(max_length=200)),
                ('taxonomy6', models.CharField(max_length=200)),
                ('taxonomy7', models.CharField(max_length=200)),
                ('taxonomy8', models.CharField(max_length=200)),
            ],
        ),
    ]
