# Generated by Django 4.0.5 on 2023-12-17 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lignindb', '0010_taxonomytb'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene', models.CharField(max_length=100)),
                ('gene_id', models.CharField(max_length=100)),
                ('protein_id', models.CharField(max_length=100)),
                ('organism', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=255)),
                ('GO_function', models.CharField(max_length=255)),
                ('GO_process', models.CharField(max_length=255)),
                ('EC_number', models.CharField(max_length=50)),
                ('GO_component', models.CharField(max_length=255)),
                ('function', models.CharField(max_length=255)),
                ('translation', models.TextField()),
                ('pathways', models.TextField()),
            ],
        ),
    ]
