# Generated by Django 4.0.5 on 2023-12-17 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lignindb', '0011_genedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genedata',
            name='EC_number',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='genedata',
            name='GO_component',
            field=models.CharField(max_length=2550),
        ),
        migrations.AlterField(
            model_name='genedata',
            name='GO_function',
            field=models.CharField(max_length=2550),
        ),
        migrations.AlterField(
            model_name='genedata',
            name='GO_process',
            field=models.CharField(max_length=2550),
        ),
        migrations.AlterField(
            model_name='genedata',
            name='function',
            field=models.CharField(max_length=2550),
        ),
        migrations.AlterField(
            model_name='genedata',
            name='gene',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='genedata',
            name='gene_id',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='genedata',
            name='organism',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='genedata',
            name='product',
            field=models.CharField(max_length=2550),
        ),
        migrations.AlterField(
            model_name='genedata',
            name='protein_id',
            field=models.CharField(max_length=1000),
        ),
    ]
