# Generated by Django 4.0.5 on 2023-12-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lignindb', '0012_alter_genedata_ec_number_alter_genedata_go_component_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genedata',
            name='EC_number',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='genedata',
            name='GO_component',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='genedata',
            name='GO_function',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='genedata',
            name='GO_process',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='genedata',
            name='function',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='genedata',
            name='gene',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='genedata',
            name='gene_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='genedata',
            name='organism',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='genedata',
            name='product',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='genedata',
            name='protein_id',
            field=models.TextField(),
        ),
    ]
